// <auto-generated />
using System;
using FoodStore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodStore.Api.Data.Migrations
{
    [DbContext(typeof(FoodStoreContext))]
    [Migration("20240228101440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("FoodStore.Api.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Harga")
                        .HasColumnType("TEXT");

                    b.Property<int>("JenisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JenisId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("FoodStore.Api.Entities.Jenis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jeniss");
                });

            modelBuilder.Entity("FoodStore.Api.Entities.Food", b =>
                {
                    b.HasOne("FoodStore.Api.Entities.Jenis", "Jenis")
                        .WithMany()
                        .HasForeignKey("JenisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jenis");
                });
#pragma warning restore 612, 618
        }
    }
}
